# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: http://192.168.31.30:8086/
    user: qx32871
    password: 1228479300
  mail:
    host: smtp.qq.com
    username: 1228479300@qq.com
    password: jnpjozrmreikgcgb
  rabbitmq:
    addresses: 192.168.31.30
    username: qx32871
    password: 123456
    virtual-host: /
  datasource:
    url: jdbc:mysql://192.168.31.30:3306/db_server_monitor
    username: root
    password: mysql_HTwEAT
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.31.30
      password: jhkdjhkjdhsIUTYURTU_s2zHQH
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 100
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
